# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-01-23 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=32, verbose_name='Место обучения')),
                ('region', models.CharField(blank=True, max_length=32, verbose_name='Регион')),
                ('site', models.CharField(blank=True, max_length=64, verbose_name='Сайт')),
                ('start_date', models.DateField(verbose_name='Период обучения')),
                ('end_date', models.DateField(verbose_name='Период обучения')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
